### ISSUE TITLE
Wire Spy sets the font for whole page

### ISSUE THREAD

**Issue by slovenianGooner** [wire-elements/wire-spy#5]
The font used in WireSpy is set over the whole html and not just in the scope of .wire-spy container.

```css
.wire-spy :host, html {
font-family: ui-sans-serif, system-ui, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
}
```
